#!/bin/bash

cd /Users/piaverous/Documents/DTY/Projet_Thales/thales-project/

cd back_django
source py36_back_env/bin/activate
cd ../ml_tools
python setup.py install > /dev/null
cd ../back_django
python src/manage.py runserver