#!/bin/bash

cd /path/to/project

cd back_django
# If you use a virtual environment : source py36_back_env/bin/activate
cd ../ml_tools
python setup.py install > /dev/null
cd ../back_django
python src/manage.py runserver