#!/bin/bash

cd /Users/pierre/Documents/DTY/thales/

cd ml_tools
source py36_ml_env/bin/activate
pip install -r requirements.txt
deactivate

cd ../back_django
source py36_back_env/bin/activate
pip install -r requirements.txt

cd ../ml_tools
python setup.py install
deactivate

cd ../front
npm install
